# Unsupervised Machine Learning
<pre>     These are of two types:-
    
      Clustering
       → K means clustering
       → Agglomarative clustering
       → Hierarchial clustering
       → Fuzzy 
    
      Associative
       → PCA( Principal Component Analysis )
       → LDA( Linear Discriminant Analysis )
</pre>

## K Means Clustering

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
iris = pd.read_csv(r"/Users/nexusop03/Downloads/iris/iris.data",header=None)
iris.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [3]:
iris.columns = ['SL','SW','PL','PW','Flower']
iris.head(3)

    SL   SW   PL   PW       Flower
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa

In [4]:
iris.isnull().sum()

SL        0
SW        0
PL        0
PW        0
Flower    0
dtype: int64

In [5]:
ip = iris.drop('Flower',axis=1)
ip.head(2)

    SL   SW   PL   PW
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2

In [ ]:
!pip uninstall scikit-learn

In [ ]:
from sklearn.cluster import KMeans
km = KMeans(n_clusters=3)
km.fit(ip)

km_pred = km.predict(ip)
km_pred

In [ ]:
centroid = km.cluster_centers_
centroid

In [ ]:
iris["Prediction"] = km_pred
iris

In [ ]:
sns.scatterplot(x=iris.SL,y=iris.PL,hue=iris['Flower'])
plt.show()

In [ ]:
sns.scatterplot(x=iris.SW,y=iris.PW,c=km_pred)
plt.show()

In [ ]:
sns.scatterplot(x=iris.SL,y=iris.PL,c=km_pred)
sns.scatterplot(x=centroid[::,0],y=centroid[::,2],s=100,color='k')
plt.show()

# TITANIC DATASET

In [ ]:
ttn = pd.read_csv(r'/Users/nexusop03/Downloads/titanic dataset.csv')
ttn

In [ ]:
ttn.isnull().sum()