#  PANDAS

In [ ]:
# Pandas is a python library which is use to analyze and manipulate the data.
# We can read and create datasets using pandas.
# Pandas is of two types:-
# (i) Series ( single column )
# (ii) Dataframe ( Multiple columns )

In [1]:
import pandas as pd

In [2]:
# Creating Series 
# List to Series
s= pd.Series(['a','b','c','d','e'])
s

0    a
1    b
2    c
3    d
4    e
dtype: object

In [3]:
type(s)

pandas.core.series.Series

In [4]:
s=pd.Series(['a','b','c','d','e'],index=[5,6,7,8,9])
s

5    a
6    b
7    c
8    d
9    e
dtype: object

In [5]:
# We can also change the index position 
s=pd.Series(['a','b','c','d','e'],index=[10,20,20,40,50])
s

10    a
20    b
20    c
40    d
50    e
dtype: object

In [6]:
s[0]

KeyError: 0

In [7]:
s[40]

'd'

In [8]:
s[20]

20    b
20    c
dtype: object

In [12]:
s[20:41:10]

Series([], dtype: object)

In [11]:
# Slicing
s[0:5:1]

10    a
20    b
20    c
40    d
50    e
dtype: object

In [17]:
# Tuple to Series
t= pd.Series((100,200,300,400))
t

0    100
1    200
2    300
3    400
dtype: int64

In [18]:
t= pd.Series((100,200,300,400),index=[10,20,30,40])
t

10    100
20    200
30    300
40    400
dtype: int64

In [20]:
t[40]

400

In [21]:
t[::2]

10    100
30    300
dtype: int64

In [22]:
t= pd.Series({100,200,300,400})
t
# We can not create a Series using Set as it is unordered.

TypeError: 'set' type is unordered

In [23]:
# Dictionary to Series
d = pd.Series({'a':1,'b':2,'c':3,'d':4})
d

a    1
b    2
c    3
d    4
dtype: int64

In [24]:
d[1:3:1]

b    2
c    3
dtype: int64

In [25]:
d1 = pd.Series({'a':1,'b':2,'c':3,'d':4},index=['e','f','a','c'])
d1

e    NaN
f    NaN
a    1.0
c    3.0
dtype: float64

In [ ]:
# NaN :- Not A Number

In [26]:
d[2]

C:\Users\bibhu\AppData\Local\Temp\ipykernel_6452\464593666.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  d[2]

3

In [27]:
d['c']

3

In [28]:
d[0:4:2]

a    1
c    3
dtype: int64

In [31]:
d['b':'d':2]

b    2
d    4
dtype: int64

In [32]:
# Creating Dataframe
# Dataframe is always created using a dictionary.

d= {'Name':['Ram','Sita','Gita','Hari','Shyam'],
   'Roll':[111,222,333,444,555],
   'Course':['AIML','PYTHON','AIML','C','JAVA']}
d

{'Name': ['Ram', 'Sita', 'Gita', 'Hari', 'Shyam'],
 'Roll': [111, 222, 333, 444, 555],
 'Course': ['AIML', 'PYTHON', 'AIML', 'C', 'JAVA']}

In [33]:
df = pd.DataFrame(d)
df

    Name  Roll  Course
0    Ram   111    AIML
1   Sita   222  PYTHON
2   Gita   333    AIML
3   Hari   444       C
4  Shyam   555    JAVA

In [34]:
type(df)

pandas.core.frame.DataFrame

In [38]:
df[2]

KeyError: 2

In [39]:
df.Name[3]

'Hari'

In [40]:
df.Course[2]

'AIML'

In [42]:
# Slicing
# iloc (index location)- used for slicing on DataFrame
# Syntax- df.iloc[row_slicing, column_slicing]
df.iloc[::,::]

    Name  Roll  Course
0    Ram   111    AIML
1   Sita   222  PYTHON
2   Gita   333    AIML
3   Hari   444       C
4  Shyam   555    JAVA

In [43]:
df.iloc[1,::]

Name        Sita
Roll         222
Course    PYTHON
Name: 1, dtype: object

In [44]:
df.iloc[::,2]

0      AIML
1    PYTHON
2      AIML
3         C
4      JAVA
Name: Course, dtype: object

In [45]:
df.iloc[::2,::]

    Name  Roll Course
0    Ram   111   AIML
2   Gita   333   AIML
4  Shyam   555   JAVA

In [46]:
# head- it represents the top rows (by default 5 )
df.head()

    Name  Roll  Course
0    Ram   111    AIML
1   Sita   222  PYTHON
2   Gita   333    AIML
3   Hari   444       C
4  Shyam   555    JAVA

In [47]:
df.head(2)

   Name  Roll  Course
0   Ram   111    AIML
1  Sita   222  PYTHON

In [49]:
# tail- it represents bottom rows(by default 5)
df.tail()

    Name  Roll  Course
0    Ram   111    AIML
1   Sita   222  PYTHON
2   Gita   333    AIML
3   Hari   444       C
4  Shyam   555    JAVA

In [50]:
df.tail(3)

    Name  Roll Course
2   Gita   333   AIML
3   Hari   444      C
4  Shyam   555   JAVA

In [51]:
# sample- it retuns random sample from the dataset ( by default 1)
df.sample()

  Name  Roll Course
0  Ram   111   AIML

In [52]:
df.sample(3)

    Name  Roll  Course
4  Shyam   555    JAVA
3   Hari   444       C
1   Sita   222  PYTHON

In [53]:
# rename
df = df.rename(columns={'Name':'Stu_Name'})
df

  Stu_Name  Roll  Course
0      Ram   111    AIML
1     Sita   222  PYTHON
2     Gita   333    AIML
3     Hari   444       C
4    Shyam   555    JAVA

In [54]:
df.set_index('Roll')

     Stu_Name  Course
Roll
111       Ram    AIML
222      Sita  PYTHON
333      Gita    AIML
444      Hari       C
555     Shyam    JAVA

In [55]:
df

  Stu_Name  Roll  Course
0      Ram   111    AIML
1     Sita   222  PYTHON
2     Gita   333    AIML
3     Hari   444       C
4    Shyam   555    JAVA

In [56]:
df=df.set_index('Roll')

In [57]:
df

     Stu_Name  Course
Roll
111       Ram    AIML
222      Sita  PYTHON
333      Gita    AIML
444      Hari       C
555     Shyam    JAVA

In [58]:
df.set_index('Roll',inplace=True)  # Because we run it second time.

KeyError: "None of ['Roll'] are in the columns"

In [59]:
df

     Stu_Name  Course
Roll
111       Ram    AIML
222      Sita  PYTHON
333      Gita    AIML
444      Hari       C
555     Shyam    JAVA

In [60]:
df=df.reset_index()
df

   Roll Stu_Name  Course
0   111      Ram    AIML
1   222     Sita  PYTHON
2   333     Gita    AIML
3   444     Hari       C
4   555    Shyam    JAVA

In [61]:
df.Course[333]

KeyError: 333

In [62]:
import numpy as np
import pandas as pd

In [63]:
df = pd.DataFrame({'Days':[1,2,3,4,5],
                  'Places':['Puri','Mathura','Asansol','Manali','Kolkata'],
                  'Visitors':[5895,5600,4859,5000,5800]})
df

   Days   Places  Visitors
0     1     Puri      5895
1     2  Mathura      5600
2     3  Asansol      4859
3     4   Manali      5000
4     5  Kolkata      5800

In [64]:
# to check missing values
df.isnull()

    Days  Places  Visitors
0  False   False     False
1  False   False     False
2  False   False     False
3  False   False     False
4  False   False     False

In [65]:
df.isnull().sum()

Days        0
Places      0
Visitors    0
dtype: int64

In [66]:
df = pd.DataFrame({'Days':[1,2,3,4,5],
                  'Places':['Puri','Mathura',np.nan,'Manali','Kolkata'],
                  'Visitors':[5895,5600,4859,5000,5800]})
df

   Days   Places  Visitors
0     1     Puri      5895
1     2  Mathura      5600
2     3      NaN      4859
3     4   Manali      5000
4     5  Kolkata      5800

In [68]:
df.isnull()

    Days  Places  Visitors
0  False   False     False
1  False   False     False
2  False    True     False
3  False   False     False
4  False   False     False

In [67]:
df.isnull().sum()

Days        0
Places      1
Visitors    0
dtype: int64

In [69]:
import warnings 
warnings.filterwarnings('ignore')

In [77]:
# fillna - to fill null values
df.Places.fillna('Puri',inplace=True)       # fillna is used only for nan
df

   Days   Places  Visitors
0     1     Puri      5895
1     2  Mathura      5600
2     3     Puri      4859
3     4   Manali      5000
4     5  Kolkata      5800

In [76]:
# to check data types of all columns
df.dtypes

Days         int64
Places      object
Visitors     int64
dtype: object

In [75]:
# to get short information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Days      5 non-null      int64
 1   Places    5 non-null      object
 2   Visitors  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [78]:
# unique
df.Places.unique()

array(['Puri', 'Mathura', 'Manali', 'Kolkata'], dtype=object)

In [79]:
df.Visitors.mean()

5430.8

In [80]:
df.Visitors.std()

472.48354468700813

In [81]:
df.Visitors.min()

4859

In [82]:
df.describe()

           Days     Visitors
count  5.000000     5.000000
mean   3.000000  5430.800000
std    1.581139   472.483545
min    1.000000  4859.000000
25%    2.000000  5000.000000
50%    3.000000  5600.000000
75%    4.000000  5800.000000
max    5.000000  5895.000000

In [86]:
df.describe(include='all')  # 'include' is use to include other datatypes

            Days Places     Visitors
count   5.000000      5     5.000000
unique       NaN      4          NaN
top          NaN   Puri          NaN
freq         NaN      2          NaN
mean    3.000000    NaN  5430.800000
std     1.581139    NaN   472.483545
min     1.000000    NaN  4859.000000
25%     2.000000    NaN  5000.000000
50%     3.000000    NaN  5600.000000
75%     4.000000    NaN  5800.000000
max     5.000000    NaN  5895.000000

In [85]:
df.describe(include='O')

       Places
count       5
unique      4
top      Puri
freq        2

# Iris Dataset

In [87]:
import numpy as np
import pandas as pd

In [89]:
iris = pd.read_csv(r"C:\Users\bibhu\Downloads\iris\iris.data")
iris

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]